import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Pan-Seared Scallops',
    description: 'Fresh scallops with parsnip puree and crispy pancetta.',
    price: 18,
    category: 'Starter',
    image: '/src/assets/images/gourmet_dish_1_1783066013173.jpg',
  },
  {
    id: '2',
    name: 'Truffle Mushroom Risotto',
    description: 'Arborio rice with wild mushrooms and black truffle shavings.',
    price: 26,
    category: 'Main',
    image: '/src/assets/images/truffle_risotto_dish_1783066341806.jpg',
  },
  {
    id: '3',
    name: 'Valrhona Chocolate Fondant',
    description: 'Warm chocolate cake with a molten center and vanilla bean ice cream.',
    price: 14,
    category: 'Dessert',
    image: '/src/assets/images/gourmet_dish_2_1783066025989.jpg',
  },
  {
    id: '4',
    name: 'The Lumière Signature',
    description: 'Smoked bourbon with spiced bitters and orange zest.',
    price: 16,
    category: 'Drink',
    image: '/src/assets/images/restaurant_cocktail_1783066040048.jpg',
  },
  {
    id: '5',
    name: 'Wagyu Beef Tartare',
    description: 'Hand-cut wagyu with capers, shallots, and a quail egg yolk.',
    price: 22,
    category: 'Starter',
    image: '/src/assets/images/wagyu_beef_tartare_starter_1783066327990.jpg',
  },
  {
    id: '6',
    name: 'Roasted Seabass',
    description: 'Line-caught seabass with braised leeks and saffron beurre blanc.',
    price: 34,
    category: 'Main',
    image: '/src/assets/images/seabass_dish_main_1783066314733.jpg',
  },
  {
    id: '7',
    name: 'Heirloom Burrata',
    description: 'Creamy burrata with seasonal tomatoes, aged balsamic, and basil oil.',
    price: 19,
    category: 'Starter',
    image: '/src/assets/images/burrata_salad_dish_1783066250882.jpg',
  },
  {
    id: '8',
    name: 'Honey-Glazed Duck',
    description: 'Roasted duck breast with cherry gastrique and parsnip crisps.',
    price: 38,
    category: 'Main',
    image: '/src/assets/images/duck_breast_dish_1783066263339.jpg',
  },
  {
    id: '9',
    name: 'Herb-Crusted Lamb',
    description: 'Rack of lamb with fondant potatoes and mint-infused jus.',
    price: 42,
    category: 'Main',
    image: '/src/assets/images/rack_of_lamb_dish_1783066275867.jpg',
  },
  {
    id: '10',
    name: 'Apple Tarte Tatin',
    description: 'Classic caramelized apple tart with Madagascar vanilla cream.',
    price: 15,
    category: 'Dessert',
    image: '/src/assets/images/tarte_tatin_dessert_1783066287642.jpg',
  },
  {
    id: '11',
    name: 'Espresso Martini',
    description: 'Freshly pulled espresso, premium vodka, and coffee liqueur.',
    price: 17,
    category: 'Drink',
    image: '/src/assets/images/espresso_martini_drink_1783066299765.jpg',
  }
];
