import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Pan-Seared Scallops',
    description: 'Fresh scallops with parsnip puree and crispy pancetta.',
    price: 18,
    category: 'Starter',
    image: 'https://images.unsplash.com/photo-1532639193859-b5d98e1c217d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    name: 'Truffle Mushroom Risotto',
    description: 'Arborio rice with wild mushrooms and black truffle shavings.',
    price: 26,
    category: 'Main',
    image: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '3',
    name: 'Valrhona Chocolate Fondant',
    description: 'Warm chocolate cake with a molten center and vanilla bean ice cream.',
    price: 14,
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    name: 'The Lumière Signature',
    description: 'Smoked bourbon with spiced bitters and orange zest.',
    price: 16,
    category: 'Drink',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '5',
    name: 'Wagyu Beef Tartare',
    description: 'Hand-cut wagyu with capers, shallots, and a quail egg yolk.',
    price: 22,
    category: 'Starter',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '6',
    name: 'Roasted Seabass',
    description: 'Line-caught seabass with braised leeks and saffron beurre blanc.',
    price: 34,
    category: 'Main',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '7',
    name: 'Heirloom Burrata',
    description: 'Creamy burrata with seasonal tomatoes, aged balsamic, and basil oil.',
    price: 19,
    category: 'Starter',
    image: 'https://images.unsplash.com/photo-1592417817098-8fd3d9ebc4a5?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '8',
    name: 'Honey-Glazed Duck',
    description: 'Roasted duck breast with cherry gastrique and parsnip crisps.',
    price: 38,
    category: 'Main',
    image: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '9',
    name: 'Herb-Crusted Lamb',
    description: 'Rack of lamb with fondant potatoes and mint-infused jus.',
    price: 42,
    category: 'Main',
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '10',
    name: 'Apple Tarte Tatin',
    description: 'Classic caramelized apple tart with Madagascar vanilla cream.',
    price: 15,
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '11',
    name: 'Espresso Martini',
    description: 'Freshly pulled espresso, premium vodka, and coffee liqueur.',
    price: 17,
    category: 'Drink',
    image: 'https://images.unsplash.com/photo-1544145945-f904253db0ad?auto=format&fit=crop&q=80&w=800',
  }
];
